### ISSUE TITLE
How use it?

### ISSUE THREAD

**Issue by petr-stety-stetka** [bhdouglass/qml-browserify#1]
I have function in javascript and in it I call some require etc...
In QML I imports (qml-browserified) javascript file, but I can't call this function, because she isn't global.
So, how can I do this function global accessible from QML or call her?

**Comment by bhdouglass** [comment]
I just updated the readme (https://github.com/bhdouglass/qml-browserify/blob/master/README.md) with better usage instructions. But you can check out the example qml/js I have setup in the "example" directory. Specifically you'll want to import the bundled file (https://github.com/bhdouglass/qml-browserify/blob/master/example/Main.qml#L3) then call your exported function using "Bundle.modules" (https://github.com/bhdouglass/qml-browserify/blob/master/example/Main.qml#L61).
