### ISSUE TITLE
Not working with facebook-chat-api module

### ISSUE THREAD

**Issue by petr-stety-stetka** [bhdouglass/qml-browserify#2]
I tried to use qml-browserify with [facebook-chat-api](https://github.com/Schmavery/facebook-chat-api) module, but unfortunately it is not working.
When I add <b>facebook-chat-api</b> into <b>dependencis</b> in <b>package.json</b> it stops working.
In QML it reports this error: _Cannot call method 'uniq' of undefined._
Can you please help me how I can get it to work?

**Comment by bhdouglass** [comment]
Can you post the command you are running, your package.json, and the function you are calling in your qml? Or just send me a link to you code?

**Comment by petr-stety-stetka** [comment]
For maximum simplification, I tried to just adjust your example.

This is my package.json:

```
{
  "name": "test-module",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "author": "Brian Douglass",
  "license": "GPL-3.0",
  "dependencies": {
    "alpha-sort": "^1.0.2",
    "facebook-chat-api": "",
    "uniq": "^1.0.1"
  }
}
```

I added **facebook-chat-api** into **dependencies** and I install latest version facebook-chat-api (from github) (so in folder _node_modules_ I have latest _facebook-chat-api_ folder etc.
Next: `qml-browserify -o bundle.js`
And I use bundle.js in QML (as in example), but it not working.
The rest is exactly the same as in your example.

I attach generated (zipped) bundle.js - broken. 
[bundle.js.zip](https://github.com/bhdouglass/qml-browserify/files/76305/bundle.js.zip)

**Comment by bhdouglass** [comment]
It looks like your package.json file is malformed, did you use the command `npm install facebook-chat-api --save` to install the facekbook chat module?

**Comment by petr-stety-stetka** [comment]
When I use command `npm install facebook-chat-api --save` result is exactly the same :(
There I attach the entire source code: [test-module.zip](https://github.com/bhdouglass/qml-browserify/files/76565/test-module.zip) and [QML example](https://github.com/bhdouglass/qml-browserify/files/76566/example.zip)

And this errors when I run QML example: 

```
file:///home/stety/example/bundle.js:30087: ReferenceError: FormData is not defined
file:///home/stety/example/Main.qml:45: TypeError: Cannot call method 'uniq' of undefined
```

**Comment by bhdouglass** [comment]
I tried getting this working by adding a FormData polyfill, it got me slightly further but it now fails because QML is missing the javascript crypto implementation. I don't believe I can get this working for you as it is a limitation in QML. Unfortunately you'll have to find another library or solution.

**Comment by petr-stety-stetka** [comment]
Ok, thank you for help. I have one more question: Can I use some JavaScript library for crypto implementation?

**Comment by bhdouglass** [comment]
I don't see why not.
